apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
spec:
  description: Contains all production applications.
  sourceRepos:
    - git@github.com:lightspeed001/devops-argocd.git
  destinations:
    - namespace: production
      server: https://kubernetes.default.svc
